### PR TITLE
Fix grammar error

### PR DESCRIPTION
**Pull request by visitorckw**
Changed 'got' to 'get' for proper grammar.

### CODE REVIEW

**Comment by cmuellner** [comment]
I'm afraid that this change is not sufficient to address all grammar mistakes in this sentence.
Probably this would be a better alternative:
> Another example is `.option arch, rv64ifd` + `.option arch, -f`, which results in `rv64ifd`, because `f` will be added back when adding the implied extensions of `d`.

**Comment by visitorckw** [comment]
Thank you for your review and suggestions!
I have made the changes accordingly.

**Review by cmuellner — APPROVED** [review]
LGTM

**Comment by cmuellner** [comment]
Thanks for the fix!

**Pull request merged**
