### PR TITLE
Add CI/CD from docs-templates repo

### PR DESCRIPTION
**Pull request by cmuellner**
This adds the CI/CD scripts from the docs-templates repo.

### CODE REVIEW

**Comment by cmuellner** [comment]
@apazos, @kito-cheng, or @wmat, please review.

**Comment by apazos** [comment]
That is what I was planning to do, to use the workflow from the docs template.
I actually pushed a draft PR and tested it in my branch: https://github.com/apazos/riscv-c-api-doc/actions/runs/12242758695
It worked fine.
But I included both *.pdf and *.html files in the artifacts. You might want to add them both. 
This means in the "Upload Build Artifacts" action, add both files:
         path: |
+            ${{ github.workspace }}/build/*.pdf
+            ${{ github.workspace }}/build/*.html

**Comment by cmuellner** [comment]
@apazos, my PRs were not meant to overtake the plans of others.

Given we had different levels of CI/CD support in the three repos (TC, CAPI, ASM), I just wanted to establish a common baseline. The background is, that we got PRs for some repos that add a dependabot action, and I want to avoid the repos diverging even more.

Feel free to provide PRs that enhance the CI/CD pipelines as you've planned.

**Comment by cmuellner** [comment]
@wmat, ping. Please approve this PR. It would be great to merge this as well.

**Review by wmat — APPROVED** [review]
LGTM thanks.

**Comment by apazos** [comment]
Hi @cmuellner, no worries. Looking at https://github.com/riscv-non-isa/riscv-asm-manual/releases, it seems it already included all the files from the build directory, both html and pdf files. I thought we would have to fix some rule to make sure they appear under Assets.

**Pull request merged**
