### PR TITLE
Standardize spelling of "pseudoinstruction"

### PR DESCRIPTION
**Pull request by zeng-xiao**

### CODE REVIEW

**Comment by cmuellner** [comment]
The change is ok for me, but it does not cover all instances:
```
riscv-asm.md:can use an `UNIMP` pseudo-instruction, which should trap in nearly all systems.
riscv-asm.md:affect the expansion of the `la` pseudoinstruction, refer to
riscv-asm.md:[listing of standard RISC-V pseudoinstructions](#pseudoinstructions).
riscv-asm.md:The following example shows the `li` pseudo instruction which
riscv-asm.md:The following example shows the `la` pseudo instruction which is used to load
riscv-asm.md:For non-PIC this is an alias for the `lla` pseudo instruction documented below.
riscv-asm.md:For PIC this is an alias for the `lga` pseudo instruction documented below.
riscv-asm.md:The `la` pseudo instruction is the preferred way for getting the address of
riscv-asm.md:The following example shows the `lla` pseudo instruction which is used to load
riscv-asm.md:The following example shows the `lga` pseudo instruction which is used to load
riscv-asm.md:The following pseudo instructions are available to load from and store to
riscv-asm.md:The following example shows how these pseudo instructions are used:
riscv-asm.md:The following pseudo instructions are available to call subroutines far from
riscv-asm.md:The following example shows how these pseudo instructions are used:
riscv-asm.md:## <a name=pseudoinstructions></a> A listing of standard RISC-V pseudoinstructions
```

Please make them all equal (`pseudoinstruction`).

**Comment by zeng-xiao** [comment]
ok, Thanks for reminding

**Review by cmuellner — APPROVED** [review]
LGTM

**Comment by cmuellner** [comment]
Merged. Thx!

**Pull request merged**
